In [2]:
import os

# get the current working directory
os.chdir("D:\ML_Practice\Skin Data")
cwd = (os.getcwd()+"/MyData")

# list all files and directories in the current working directory
files_and_directories = os.listdir(cwd)


# filter the list to only include directories (i.e., exclude files)
folder_names = [f for f in files_and_directories if os.path.isdir(os.path.join(cwd, f))]

print(folder_names)  # prints a list of the directories in the current working directory


['Acne and Rosacea Photos', 'Actinic Keratosis Basal Cell Carcinoma and other Malignant Lesions', 'Atopic Dermatitis Photos', 'Bullous Disease Photos', 'Cellulitis Impetigo and other Bacterial Infections', 'Eczema Photos', 'Exanthems and Drug Eruptions', 'Hair Loss Photos Alopecia and other Hair Diseases', 'Herpes HPV and other STDs Photos', 'Light Diseases and Disorders of Pigmentation', 'Lupus and other Connective Tissue diseases', 'Melanoma Skin Cancer Nevi and Moles', 'Nail Fungus and other Nail Disease', 'Poison Ivy Photos and other Contact Dermatitis', 'Psoriasis pictures Lichen Planus and related diseases', 'Scabies Lyme Disease and other Infestations and Bites', 'Seborrheic Keratoses and other Benign Tumors', 'Tinea Ringworm Candidiasis and other Fungal Infections', 'Urticaria Hives', 'Vascular Tumors', 'Vasculitis Photos', 'Warts Molluscum and other Viral Infections']


In [52]:

from PIL import Image,ImageOps
import numpy as np
import cv2


X = []  # list to store the images
y = []  # list to store the labels
img_Size=64

for i, folder_name in enumerate(folder_names):
    # navigate to the folder
    path = os.path.join(cwd, folder_name)
    os.chdir(path)

    # open all images in the folder
    for file in os.listdir(path):
        if file.endswith('.jpg'):
            image = cv2.imread(file,cv2.IMREAD_GRAYSCALE)
            image = cv2.resize(image,(img_Size,img_Size))
            # you can do something with the image here, such as preprocessing it for neural network training
            X.append(image)
            y.append(i)  # append the label for the image (i.e., the index of the folder)

# convert the lists to numpy arrays
X = np.array(X).reshape(-1,img_Size,img_Size,1)
y = np.array(y)

In [53]:
X=X/255
from sklearn.utils import shuffle
X_train,y_Train = shuffle(X,y)

y_Train
# from sklearn.model_selection import train_test_split
# X_Train,X_Test,y_Train,y_Test = train_test_split(X,y,test_size=0.1,shuffle=True)
# print(y_Train,y_Test)

array([16,  5,  0, ..., 16, 21,  5])

In [36]:
len(X_train)

14951

In [5]:
import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow import keras
from tensorflow.keras.layers import Dense

In [57]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

# Initialize the CNN
model = Sequential()

# Add the first convolutional layer
model.add(Conv2D(32, (3, 3), input_shape = (img_Size, img_Size, 1), activation = 'relu'))

# Add a max pooling layer
model.add(MaxPooling2D(pool_size = (2, 2)))

# Add a second convolutional layer
model.add(Conv2D(32, (3, 3), activation = 'relu'))

# Add a second max pooling layer
model.add(MaxPooling2D(pool_size = (2, 2)))

# Add a flattening layer
model.add(Flatten())

# Add a fully connected layer
model.add(Dense(units = 128, activation = 'relu'))

# Add an output layer
model.add(Dense(units = 22, activation = 'softmax'))

In [58]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [59]:
model.fit(X_train,y_Train,epochs=50)

Epoch 1/50
121/121 [==============================] - 6s 48ms/step - loss: 2.9151 - accuracy: 0.1091
Epoch 2/50
121/121 [==============================] - 6s 47ms/step - loss: 2.8167 - accuracy: 0.1421
Epoch 3/50
121/121 [==============================] - 6s 48ms/step - loss: 2.7597 - accuracy: 0.1584
Epoch 4/50
121/121 [==============================] - 6s 52ms/step - loss: 2.6924 - accuracy: 0.1800
Epoch 5/50
121/121 [==============================] - 6s 50ms/step - loss: 2.6130 - accuracy: 0.2101
Epoch 6/50
121/121 [==============================] - 6s 50ms/step - loss: 2.5104 - accuracy: 0.2397
Epoch 7/50
121/121 [==============================] - 6s 51ms/step - loss: 2.3946 - accuracy: 0.2782
Epoch 8/50
121/121 [==============================] - 6s 50ms/step - loss: 2.2718 - accuracy: 0.3114
Epoch 9/50
121/121 [==============================] - 6s 51ms/step - loss: 2.1279 - accuracy: 0.3488
Epoch 10/50
121/121 [==============================] - 6s 50ms/step - loss: 1.9698 - accura

In [60]:
os.chdir("D:\ML_Practice\Skin Data")

cwds=os.getcwd()+"/test"

# list all files and directories in the current working directory
files_and_directories_test = os.listdir(cwds)

# filter the list to only include directories (i.e., exclude files)
folder_names_test = [f for f in files_and_directories_test if os.path.isdir(os.path.join(cwds, f))]

print(folder_names_test)  # prints a list of the directories in the current working directory

['Acne and Rosacea Photos', 'Actinic Keratosis Basal Cell Carcinoma and other Malignant Lesions', 'Atopic Dermatitis Photos', 'Bullous Disease Photos', 'Cellulitis Impetigo and other Bacterial Infections', 'Eczema Photos', 'Exanthems and Drug Eruptions', 'Hair Loss Photos Alopecia and other Hair Diseases', 'Herpes HPV and other STDs Photos', 'Light Diseases and Disorders of Pigmentation', 'Lupus and other Connective Tissue diseases', 'Melanoma Skin Cancer Nevi and Moles', 'Nail Fungus and other Nail Disease', 'Poison Ivy Photos and other Contact Dermatitis', 'Psoriasis pictures Lichen Planus and related diseases', 'Scabies Lyme Disease and other Infestations and Bites', 'Seborrheic Keratoses and other Benign Tumors', 'Tinea Ringworm Candidiasis and other Fungal Infections', 'Urticaria Hives', 'Vascular Tumors', 'Vasculitis Photos', 'Warts Molluscum and other Viral Infections']


In [62]:
X_Test = []  # list to store the images
y_Test = []  # list to store the labels
img_Size=64

for i, folder_name in enumerate(folder_names):
    # navigate to the folder
    path = os.path.join(cwds, folder_name)
    os.chdir(path)

    # open all images in the folder
    for file in os.listdir(path):
        if file.endswith('.jpg'):
            image = cv2.imread(file,cv2.IMREAD_GRAYSCALE)
            image = cv2.resize(image,(img_Size,img_Size))
            # you can do something with the image here, such as preprocessing it for neural network training
            X_Test.append(image)
            y_Test.append(i)  # append the label for the image (i.e., the index of the folder)

# convert the lists to numpy arrays
X_Test = np.array(X_Test).reshape(-1,img_Size,img_Size,1)
y_Test = np.array(y_Test)

In [63]:
len(X_Test)
X_Test = X_Test/255

In [64]:
predicted=model.predict(X_Test)

121/121 [==============================] - 2s 16ms/step


In [65]:
predicted


array([[9.8819274e-01, 1.0562189e-06, 8.9175272e-05, ..., 5.5360946e-05,
        6.8572740e-07, 2.2761228e-03],
       [9.9996793e-01, 4.6823998e-14, 3.1813122e-11, ..., 1.1535463e-07,
        1.6524945e-10, 2.6103399e-08],
       [9.3753809e-01, 4.5402849e-08, 1.0529830e-06, ..., 4.2752360e-04,
        1.5096862e-07, 1.5630880e-05],
       ...,
       [4.0905683e-09, 7.8799218e-05, 1.9212159e-03, ..., 4.0186041e-08,
        1.2537981e-05, 9.5526916e-01],
       [5.7281729e-13, 3.8422789e-11, 1.3978309e-03, ..., 3.8023218e-10,
        1.2214567e-12, 9.9854761e-01],
       [2.0211090e-04, 5.9657843e-05, 5.4673816e-04, ..., 1.5192104e-03,
        2.1755133e-07, 9.7610384e-01]], dtype=float32)

In [66]:
predicted_result =[]
predicted_right=0
predicted_wrong=0
for i in range(len(predicted)):
    for j in range(22):
        if max(predicted[i])==predicted[i][j]:
            if j == y_Test[i]:
                predicted_right+=1
            else:
                predicted_wrong+=1    
            predicted_result.append(j)
print("Total Test Data = {}\nPredicted Right = {}\nPredicted Wrong = {}".format(len(predicted),predicted_right,predicted_wrong))               
        

Total Test Data = 3850
Predicted Right = 3819
Predicted Wrong = 31


In [67]:
model.evaluate(X_Test,y_Test)

 

121/121 [==============================] - 2s 16ms/step - loss: 0.0437 - accuracy: 0.9919


[0.04369794577360153, 0.9919480681419373]

In [70]:
from sklearn import metrics
f1_score = metrics.f1_score(y_Test, predicted_result,average="weighted")
f1_score

0.99198752291008

In [33]:

os.chdir("D:\ML_Practice\Skin Data")
model.save('my_model.h5')




468/468 [==============================] - 5s 10ms/step


array([[9.90683556e-01, 1.86356761e-08, 2.28861245e-06, ...,
        1.19012265e-11, 9.69581748e-09, 2.97284988e-03],
       [9.81785178e-01, 2.13284045e-03, 2.90340640e-10, ...,
        2.25399802e-07, 2.88669777e-13, 2.02140859e-06],
       [8.44561279e-01, 1.80824936e-04, 2.53921412e-10, ...,
        2.47138061e-08, 2.34923618e-06, 1.45534247e-01],
       ...,
       [1.51833677e-21, 1.21635883e-24, 3.35227814e-17, ...,
        3.09116580e-03, 3.22190694e-20, 9.71621633e-01],
       [8.57486478e-12, 2.90868774e-09, 1.91548595e-21, ...,
        3.82450125e-08, 2.25410389e-07, 9.99743998e-01],
       [2.46896111e-14, 2.45407722e-11, 4.93291871e-17, ...,
        1.20886618e-13, 7.58479390e-12, 9.99999881e-01]], dtype=float32)